export enum Routes {
  viewProfile = "Profilo",
  viewHome = "Home",
  viewSearch = "Cerca",
  viewRoomDetail = "Room Detail",
  viewRoomList = "Chat",
  viewCallList = "Call List",
  viewLogin = "Login",
  viewForgotPassword = "Password dimenticata",
  viewForgotPasswordSuccess = "Password cambiata con successo",
  viewSignup = "Signup",
  viewSignupSuccess = "Signup Success",
  viewUserList = "User List",
  viewNewGroupRoom = "Create New Group Room",
  viewNewGroupCall = "Create New Group Call",
  viewNewRoom = "Create New Room",
  viewGoogleMap = 'GoogleMapLocation',
}
